#===============================================================================================
# ZSCODE Custom Configuration Properties
#===============================================================================================
zscode:
   service:
      organisation:
         name: Zafritech (Pty) Ltd
         domain: zafritech.net
         
spring:
   artemis:
      user: artemis
      password: simetraehcapa