#===============================================================================================
# ZSCODE Custom Configuration Properties
#===============================================================================================
spring:
   artemis:
      user: {cipher}93e10d10c20c27dfaa95c368eeafc7a53be7f3af32c563d6bde1f44114021fd9
      password: {cipher}5bc2ad077ab8431734ed23815914d307bebc07cee523b316639589714c80fd96
      
zscode:
   service:
      organisation:
         name: Zafritech (Pty) Ltd
         domain: zafritech.net
   services:
      base-url: http://localhost:8762/users/v1/
      auth-url: http://localhost:8762/users/v1/auth/applications
      spaces-url: http://localhost:8762/spaces/v1/
      api: /applications
      auth: /auth/applications
      signup: /signup
      login: /login
      identity: /identity
      communication: jms
   urls:
      gateway-url: http://localhost:8762/
      accounts-api: http://localhost:8762/accounts/v1/
      auth-api: http://localhost:8762/accounts/v1/auth/
      spaces-api: http://localhost:8762/spaces/v1/
      cms-api: http://localhost:8762/cms/v1/api/
      cms-url: http://localhost:8762/cms/v1/
      cms-images: images/id/
      signup-path: register
      login-path: login

