#===============================================================================================
# ZSCODE Custom Configuration Properties
#===============================================================================================
zscode.service.organisation.name=Zafritech (Pty) Ltd
zscode.service.organisation.domain=zafritech.net