spring:
   datasource:
      initialization-mode: ALWAYS
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/zscodecmsdb?autoReconnect=true&useSSL=false&nullCatalogMeansCurrent=true
      username: zscodedbuser
      password: X4Kvti6FCgVZyVph
      hikari:
         connection-timeout: 20000
         minimum-idle: 5
         maximum-pool-size: 12
         idle-timeout: 300000
         max-lifetime: 1200000
         auto-commit: true        
   jpa:
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQL57Dialect
            new_generator_mappings: false
            format_sql: true 
            search.lucene_version: LATEST
      hibernate:
         ddl-auto: update
#        ddl-auto: create
#        ddl-auto: create-drop
   servlet:
      multipart:
         max-file-size: 128MB
         max-request-size: 128MB
         enabled: true

zscode:
   application:
      email: cms@zafritech.net
      name: cms
      title: Content Management System
      description: Content management system (CMS) provides storage of digital assets to all other services.
      version: v1.0.2
      released: 2021-03-27
      license: GNU General Public License v3.0
      base-url: http://localhost:8762/cms/
      data-dir: /home/lukes/src/resources/cms-service/data/
      upload-dir: /home/lukes/src/uploads/
      images-dir: /home/lukes/src/resources/cms-service/images/
      static-resources: /home/lukes/src/resources/cms-service/images/
      restrict-ips: FALSE
      allowed-ips: 127.0.0.1,82.29.194.234,167.99.40.177,192.168.0.14
      api-key: UyqRsPuFxxJGDV2ywzbEsaNGgTa5ps75
      default-delay: 30000
